version: '3'
services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: "wordict"
      POSTGRES_USER: "wordict"
      POSTGRES_PASSWORD: "wordict"
    volumes:
      - wordict-volume:/var/lib/postgresql/data
volumes:
  wordict-volume: