CREATE TABLE IF NOT EXISTS users(
   id VARCHAR NOT NULL PRIMARY KEY,
   email VARCHAR NOT NULL UNIQUE,
   password VARCHAR NOT NULL,
   created_at TIMESTAMP DEFAULT now(),
   updated_at TIMESTAMP DEFAULT now()
);